mysql1:
  image: mysql:latest
  expose:
   - "3306"
  environment:
   - MYSQL_ROOT_PASSWORD=123456
   - MYSQL_DATABASE=kingshard

mysql2:
  image: mysql:latest
  expose:
   - "3306"
  environment:
   - MYSQL_ROOT_PASSWORD=123456
   - MYSQL_DATABASE=kingshard

kingshard:
  image: kingshard
  volumes:
    - .:/go/src/github.com/flike/kingshard/etc
  ports:
    - "9696:9696"
  expose:
    - "9696"
  links:
    - mysql1
    - mysql2
  entrypoint: ./etc/wait-for-it.sh mysql2:3306 -- kingshard " -config=./etc/ks1.yaml"

