version: '2'

services:

  management1:
    image: mysql/mysql-cluster
    volumes:
       - ./mysql.conf/my.cnf:/etc/my.cnf
       - ./mysql.conf/mysql-cluster.cnf:/etc/mysql-cluster.cnf
    command: ndb_mgmd
    networks:
      mysqlcluster:
        ipv4_address: 172.28.0.2
  
  ndb1:
    image: mysql/mysql-cluster
    volumes:
       - ./mysql.conf/my.cnf:/etc/my.cnf
       - ./mysql.conf/mysql-cluster.cnf:/etc/mysql-cluster.cnf
    command: ndbd
    depends_on:
      - "management1"
    networks:
      mysqlcluster:
        ipv4_address: 172.28.0.3

  ndb2:
    image: mysql/mysql-cluster
    volumes:
       - ./mysql.conf/my.cnf:/etc/my.cnf
       - ./mysql.conf/mysql-cluster.cnf:/etc/mysql-cluster.cnf

    command: ndbd
    depends_on:
      - "management1"
    networks:
      mysqlcluster:
        ipv4_address: 172.28.0.4
  
  mysql1:
    image: mysql/mysql-cluster
    ports:
      - "3306:3306"
    volumes:
       - ./mysql.conf/my.cnf:/etc/my.cnf
       - ./mysql.conf/mysql-cluster.cnf:/etc/mysql-cluster.cnf
    environment:
      MYSQL_ROOT_PASSWORD: mypassword
      MYSQL_DATABASE: pucsddatabase
      MYSQL_USER: pucsd
      MYSQL_PASSWORD: pucsd
      MYSQL_ROOT_HOST: '%'
    command: mysqld
    depends_on:
      - "management1"
      - "ndb1"
      - "ndb2"
    networks:
      mysqlcluster:
        ipv4_address: 172.28.0.10
  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
    links:
      - mysql1:db
    networks:
      mysqlcluster:

networks:
 mysqlcluster:
  driver: bridge
  ipam:
   config:
    - subnet: 172.28.0.0/16
      gateway: 172.28.5.254